### ISSUE TITLE
No URL encoding when loading tables from HTTP

### ISSUE THREAD

**Issue by akariv** [datapackages/datapackage-py#35]
When a resource name contains spaces, the URL that is being passed to tabulator is invalid - it should be percent encoded.

**Comment by vitorbaptista** [comment]
In my opinion, this bug is actually in Tabulator. Tabulator's users shouldn't need to encode URLs; it should be done by Tabulator itself. This is how Requests work, for example.

I opened issue https://github.com/datapackages/tabulator-py/issues/42 about it.

**Comment by pwalsh** [comment]
@vitorbaptista agreed.

**Comment by akariv** [comment]
I actually thought the same at first, but then realised that tabulator should get valid URLs and cannot be faulted when an invalid URL is handled. And a URL cannot contain spaces - it is an invalid character.

The fact that requests does 'autocorrect' to its inputs doesn't mean that we should count on this behaviour, or encourage it. 

See for example:
```
>>> requests.get('http://google.com/?q=a b c')
<Response [200]>
```

But 
```
>>> urllib2.urlopen('http://google.com/?q=a b c')
<snip>
urllib2.HTTPError: HTTP Error 400: Bad Request
```

**Comment by vitorbaptista** [comment]
Well, the same argument could be used for `datapackage-py`: it expects to receive a valid URL :smile: 

Trying to follow the principle of "be generous with input, strict with output", I looked into how difficult it would be to implement in DataPackage as well. It turned out to be quite a rabbit hole.

There are many corner cases to encoding an URL. The best method I've found to do it was `requests.utils.requote_uri`. I could do that before sending an URL to `tabulator`, but as the code currently doesn't differentiate between sending a URL or a local path, I would have to change that as well (I can't encode a `/foo/foo bar.csv` to `/foo/foo%20bar.csv`).

It seems to me the easiest solution would be changing tabulator to use `requests` :+1:

**Comment by akariv** [comment]
Well, the main difference is that `datapackage-py` doesn't get a URL but parts which it has to then use to build a valid URL...

But I guess that I must agree that the simplest solution is to upgrade to `requests` :smile:

**Comment by vitorbaptista** [comment]
Oh, I get it now. You're saying in the case that the datapackage is at (say) `http://someplace.com/datapackage.json` and has:

```json
{
    "name": "foo",
    "resources": [
        { "url": "data/some data.csv" }
    ]
}
```

Then we need to join that with the base path to generate "http://someplace.com/data/some data.csv".

I was thinking in the case that the datapackage.json is:

```json
{
    "name": "foo",
    "resources": [
        { "url": "http://someotherplace.com/data/some data.csv" }
    ]
}
```

i.e. the entire url is at `resources[0].url`.

That's an interesting corner case. For example, say that in the first `datapackage.json` we had:

```json
{
    "name": "foo",
    "resources": [
        { "path": "data/some data.csv" }
    ]
}
```

If the `datapackage.json` is loaded locally, that path points to a local path (say `/home/foo/data/some data.csv`) and can't be changed, but if `datapackage.json` is loaded remotely, that path points to a remote path, and must be encoded. There's even the question on how to handle Windows, where "data/some data.csv" won't work because of the path separator.

There are many situations then:

* If `datapackage.json` is in the local filesystem:
  * Load the file taking care to change the path separators depending on the operating system;
* If not:
  * If it has an `url`;
    * If it's a relative URL, generate it with `datapackage.json` base path (should we encode it, or rely on the user to give a valid URL?)
  * If not, generate the URL using `path` and encode it.

Not sure what to do with it. Just some food for thought.
